services:
  - type: web
    name: taskapp
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn taskapp.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.3
      - key: DEBUG
        value: "0"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: taskapp.onrender.com
